### ISSUE TITLE
Share and Like function [Dev-5.0]

### ISSUE THREAD

**Issue by hstaatsxx** [ConstructiveNews/squirrel-news-app#29]
**Updated issue see https://github.com/ConstructiveNews/squirrel-news-app/issues/29#issuecomment-1373476199**

~~User story:
**As a** User
**I want** a UI element
**So that** I have the ability to like and share articles~~

~~Acceptance criteria:
_Given_ the user is on an article teaser
_When_ he clicks on the like button located under the teaser image
_Then_ the article gets saved to his favorites~~

~~_Given_ the user is on an article teaser
_When_ he clicks on the share button located under the teaser image
_Then_ the OS share menu is opened up~~

~~Dependencies:
Burger Menu [Dev-2.0]~~

~~Reference:~~

![Image](https://user-images.githubusercontent.com/44089084/201297149-5f107ba5-ad65-4a5b-9886-154d64b8f5e9.png)

~~Description:
As we're getting rid of the navigation bar on the bottom of the app, we need a new way for users to share (and like / fav) articles. Our idea was to do that via a floating action button (FAB). However, on the teaser screens, this would probably hide some teaser text; on the article view it is more difficult to implement. This can be solved though.
A rough layout idea already exists. Can be refined though. In the future we would also want integrate a reference to squirrel news.~~

**Comment by hstaatsxx** [comment]
Share and Like functions will be displayed between the image and headline - instagram-like ui

**Comment by DevJacobi** [comment]
Update: Like in the PR for this issue mentioned [here](https://github.com/ConstructiveNews/squirrel-news-app/pull/31#issuecomment-1326387921), we need to clarify with Jonathan and Oli the final desgin

**Comment by pfkeen** [comment]
@constructive-news 
This one is stil waiting since first sprint and it would be nice to get some further instructions.
- Like icon either heart or bookmark?
- placing share and like icons?
Specific icons would be great here.

**Comment by constructive-news** [comment]
We're still / again working on the placement with a new designer. Won't be ready before next week though. As we have a bookmark icon in the menu now, we'll have one here, too for the fav function.

**Comment by grollk** [comment]
User story:
**As a** User
**I want** centrally located UI elements
**So that** I have the ability to like and share articles

Acceptance criteria:
_Given_ the user is on an article teaser
_Then_ the bookmark/like and share elements are located at the bottom of the article teaser
_And_ are visually separated from the rest of the article teaser by a horizontal line
_And_ they belong to the article teaser, moving accordingly when scrolling/swiping

_Given_ the user is on an article teaser
_When_ he clicks on the like button located under the teaser image
_Then_ the article gets saved to his favorites

_Given_ the user is on an article teaser
_When_ he clicks on the share button located under the teaser image
_Then_ the OS share menu is opened up

Mockup:
_For the full reference see figma_
![Image](https://user-images.githubusercontent.com/44089084/211000016-af0a8b67-3547-4591-9fbc-22f0d0fff150.png)


Dependencies:
#44 

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by hstaatsxx** [comment]
The current error with the share function will be handled in another issue.

**Comment by hstaatsxx** [comment]
## Documentation
### Short description of the change
Share and Favourite buttons are added to the teaser issue page based on the Figma mockup.

### Codebase Changes
A horizontal line with CSS class is added to the ArticleTeaser page. Share and Favourite buttons are added below the horizontal line. Functions behind these icons were given already.

### Visual Documentation
<img width="377" alt="Bildschirmfoto 2023-02-05 um 16 20 57" src="https://user-images.githubusercontent.com/31039939/216828129-3540dac2-6a76-4ec6-9d63-0cb99e123d10.png">
