### ISSUE TITLE
Scroll Navigation [Dev-12.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#44]
User story:
**As a** user
**I want** the ability to navigate articles by scrolling instead of swiping
**So that** I can choose a navigation style, according to my preference

Acceptance criteria:
_Given_  the issue navigation is reworked
_When_ scroll and swipe navigation are implemented
_Then_ the swiper.js library is used

_Given_ the issue navigation is reworked
_When_ swipe navigation is implemented
_Then_ swipe contains pagination

_Given_ the issue navigation is reworked
_When_ scroll navigation is implemented
_Then_ scroll does not contain pagination

Dependencies:
none

Description:
Users have repeatedly criticized the swipe function. Some like it though. Our idea: Introduce an scroll function in addition and let users decide (via a settings menu) what they prefer.

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by hstaatsxx** [comment]
### Documentation
**Short description of the change**

This issue and issue #57 are implemented in one branch. 
The implementation enables vertical and horizontal swipe functions depending on user setting for the swipe action.
The vertical version of swipe does not show any pagination since it will be overlapped with the article image and might disturb viewers during the reading the article.

**Codebase Changes**
A new Swiperview.tsx component is created and replaced in BasicLayout with the existing Scollview.tsx.
Rendering pages stayed the same: IssueCoverPage, all ArticleTeasers, DonationPage, and MorePage.
Just like other toggle settings the toggle for swiping works via AppContext, which is saved in storage.
Base on the saved toggle swipe setting, the rendering of component will differ slightly with direction and pagination flag.

**Visual Documentation**

https://user-images.githubusercontent.com/31039939/211852250-96a17822-c3a4-4472-8ada-7c2a4d599225.mov

**Comment by DevJacobi** [comment]
@hstaatsxx I merged the PR. Don't forget to add documentation. Same for the other related issue
